name: devsecops-pipeline
on: [push, pull_request]

jobs:
  secrets:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Download and run Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.4_linux_x64.tar.gz
          ./gitleaks detect --source . --config gitleaks.toml --verbose --no-git
        continue-on-error: false
