name: devsecops-pipeline
on: [push, pull_request]

jobs:
  secrets:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Gitleaks STRICT
        shell: pwsh
        run: |
          # Escaneo estricto sin archivo de configuración
          ./gitleaks.exe detect --source . --verbose --no-git --exit-code 1
          
          # También escanea específicamente los .env
          Get-ChildItem -Path . -Filter .env -Recurse | ForEach-Object {
            Write-Host "Scanning: $($_.FullName)"
            ./gitleaks.exe detect --source $_.FullName --verbose --no-git
          }
